In [37]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split,KFold


In [38]:
df = load_digits()

In [39]:
x_train,x_test,y_train,y_test = train_test_split(df.data, df.target, test_size=0.2)

In [40]:
x_train

array([[ 0.,  0.,  0., ...,  9.,  0.,  0.],
       [ 0.,  0.,  0., ...,  6.,  0.,  0.],
       [ 0.,  0.,  9., ..., 16.,  6.,  0.],
       ...,
       [ 0.,  0.,  6., ...,  0.,  0.,  0.],
       [ 0.,  0.,  6., ...,  0.,  0.,  0.],
       [ 0.,  1., 13., ..., 14.,  3.,  0.]])

In [41]:

def get_score(model,x_train,y_train,x_test,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)
   
    
    

In [42]:
get_score(LogisticRegression(),x_train,y_train,x_test,y_test)


/home/salmaa/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9583333333333334

In [43]:

get_score(RandomForestClassifier(n_estimators=50),x_train,y_train,x_test,y_test)

0.95

In [44]:
get_score(SVC(),x_train,y_train,x_test,y_test)

0.9777777777777777

In [57]:
df.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [60]:
df.data.shape

(1797, 64)

In [75]:
score_svm=[]
for train_index, test_index in kf.split(df.data):
    print(train_index.shape)
    x_train = df.data[train_index]
    print(x_train.shape)
    y_train = df.target[train_index]
    
    x_test = df.data[test_index]
    y_test= df.target[test_index]
    
    model =SVC()
    model.fit(x_train, y_train)
    score_svm.append(model.score(x_test,y_test))

(1437,)
(1437, 64)
(1437,)
(1437, 64)
(1438,)
(1438, 64)
(1438,)
(1438, 64)
(1438,)
(1438, 64)


In [69]:
print(score_svm)

[0.9916666666666667, 0.9861111111111112, 0.9888579387186629, 0.9832869080779945, 0.9888579387186629]


In [71]:
np.mean(score_svm)

0.9877561126586197

In [73]:
model.predict(x_test)

array([2, 1, 3, 7, 6, 0, 8, 9, 0, 8, 3, 3, 6, 4, 5, 0, 3, 7, 4, 3, 1, 6,
       5, 2, 9, 8, 9, 1, 2, 5, 8, 1, 4, 5, 8, 8, 8, 1, 7, 8, 1, 3, 6, 6,
       2, 1, 9, 3, 6, 2, 6, 7, 8, 4, 7, 0, 8, 1, 0, 2, 6, 3, 7, 4, 1, 4,
       1, 7, 0, 6, 7, 8, 3, 0, 8, 7, 0, 1, 3, 9, 5, 7, 0, 2, 8, 1, 3, 6,
       1, 0, 0, 1, 6, 4, 3, 3, 9, 5, 5, 4, 2, 7, 5, 9, 2, 8, 6, 8, 8, 3,
       3, 6, 1, 2, 7, 4, 6, 8, 4, 0, 5, 9, 4, 7, 4, 8, 7, 9, 1, 3, 4, 7,
       2, 7, 8, 0, 3, 1, 0, 8, 3, 6, 1, 8, 1, 9, 1, 6, 7, 4, 7, 2, 8, 2,
       5, 9, 8, 0, 2, 5, 6, 7, 2, 6, 7, 0, 6, 7, 8, 0, 5, 9, 1, 1, 8, 2,
       3, 3, 1, 8, 7, 7, 8, 4, 3, 9, 5, 4, 2, 4, 1, 4, 7, 0, 5, 7, 5, 5,
       5, 9, 9, 1, 6, 4, 1, 4, 3, 7, 7, 2, 9, 8, 3, 9, 1, 1, 5, 6, 1, 0,
       2, 4, 6, 4, 9, 5, 0, 1, 7, 9, 5, 8, 9, 6, 8, 2, 5, 6, 9, 7, 1, 0,
       0, 7, 8, 7, 9, 5, 2, 0, 7, 6, 1, 6, 6, 9, 7, 5, 8, 9, 0, 6, 8, 9,
       5, 5, 5, 8, 4, 1, 5, 8, 0, 3, 9, 7, 2, 7, 1, 7, 3, 9, 6, 4, 8, 9,
       0, 7, 0, 2, 3, 4, 8, 7, 5, 1, 7, 7, 6, 9, 2,